version: "3.7"
services:
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    image: mariadb
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
  backend:
    build:
      args:
        - NODE_ENV=development
      context: backend
    command: npm run start-watch
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    networks:
      - public
      - private
    depends_on:
      - db
    restart: on-failure:5
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
